version: "2"
services:
    db:
        container_name: mariadb
        hostname: mariadb
        image: mariadb
        ports:
          - "3306:3306"
        restart: always
        environment:
          MYSQL_DATABASE: testDB
          MYSQL_USER: neon
          MYSQL_PASSWORD: neon
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - persistent:/var/lib/mysql
          - ./files:/files
        networks:
          - default
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        hostname: pma
        links:
          - db:db
        ports:
          - 8000:80
        restart: always
        environment:
          MYSQL_USER: neon
          MYSQL_PASSWORD: neon
          MYSQL_ROOT_PASSWORD: root
          UPLOAD_LIMIT: 2000M
volumes:
    persistent:
